environment_config:
  path: src/app/config/prod_environment_config.dart
  class: ProductionConfig

  fields:
    configName:
      type: String
      default: production
    baseUrl:
      type: String
      default: https://prodhost:8081/
    v1RouteUrl:
      type: String
      default: https://prodhost:8081/v1/
    connectTimeout:
      type: int
      default: 30000
    receiveTimeout:
      type: int
      default: 30000
    defaultLocale:
      type: String
      default: ru_RU