name: financial_management
description: "Financial management and assistant application"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  auto_route: ^8.1.3
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  dio: ^5.4.3+1
  pincode_input_fields: ^1.0.2
  lottie: ^3.1.0
  environment_config: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  scrollable_date_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  hive_generator: ^2.0.0

flutter_gen:
  output: lib/src/app/assets_gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter:

  assets:
    - assets/icons/
    - assets/lang/
    - assets/logo/
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/lottie/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400

  uses-material-design: true