environment_config:
  path: src/app/config/stage_environment_config.dart
  class: StagingConfig

  fields:
    configName:
      type: String
      default: staging
    baseUrl:
      type: String
      default: https://stagehost:8081/
    v1RouteUrl:
      type: String
      default: https://stagehost:8081/v1/
    connectTimeout:
      type: int
      default: 30000
    receiveTimeout:
      type: int
      default: 30000
    defaultLocale:
      type: String
      default: ru_RU